'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Acquisti
    Public Property IDAcquisto As Integer
    Public Property Data As Date
    Public Property Transazione As Integer

    Public Overridable Property Fornitori As Fornitori
    Public Overridable Property Oggetti As ICollection(Of Oggetti) = New HashSet(Of Oggetti)

End Class
