'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Fornitori
    Public Property IDFornitore As Integer
    Public Property Cognome As String = " "
    Public Property Nome As String = " "
    Public Property RifDoc As String = " "
    Public Property Indirizzo As String = " "
    Public Property Citta As String = " "
    Public Property Provincia As String = " "
    Public Property Telefono As String = " "
    Public Property Cap As String = " "
    Public Property TipoDoc As String = " "
    Public Property DataRilascio As Date
    Public Property DataNascita As Date
    Public Property Note As String = " "

    Public Overridable Property Acquisti As ICollection(Of Acquisti) = New HashSet(Of Acquisti)

End Class
