
'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.ComponentModel
Imports System.Data.EntityClient
Imports System.Data.Objects
Imports System.Data.Objects.DataClasses
Imports System.Linq
Imports System.Runtime.Serialization
Imports System.Xml.Serialization


<Assembly: EdmSchemaAttribute("54529e3f-878e-4027-b50b-85c470ed91d1")>
#Region "EDM Relationship Metadata"
<Assembly: EdmRelationshipAttribute("MRCashModel", "FK_Acquisti_Fornitori", "Fornitori", System.Data.Metadata.Edm.RelationshipMultiplicity.One, GetType(Fornitori), "Acquisti", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, GetType(Acquisti))>
<Assembly: EdmRelationshipAttribute("MRCashModel", "FK_Oggetti_Acquisti", "Acquisti", System.Data.Metadata.Edm.RelationshipMultiplicity.One, GetType(Acquisti), "Oggetti", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, GetType(Oggetti))>
<Assembly: EdmRelationshipAttribute("MRCashModel", "FK_Oggetti_Vendite", "Vendite", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, GetType(Vendite), "Oggetti", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, GetType(Oggetti))>

#End Region

#Region "Contexts"

''' <summary>
''' No Metadata Documentation available.
''' </summary>
Public Partial Class MRCashEntities
    Inherits ObjectContext

    #Region "Constructors"

    ''' <summary>
    ''' Initializes a new MRCashEntities object using the connection string found in the 'MRCashEntities' section of the application configuration file.
    ''' </summary>
    Public Sub New()
        MyBase.New("name=MRCashEntities", "MRCashEntities")
        OnContextCreated()
    End Sub

    ''' <summary>
    ''' Initialize a new MRCashEntities object.
    ''' </summary>
    Public Sub New(ByVal connectionString As String)
        MyBase.New(connectionString, "MRCashEntities")
        OnContextCreated()
    End Sub

    ''' <summary>
    ''' Initialize a new MRCashEntities object.
    ''' </summary>
    Public Sub New(ByVal connection As EntityConnection)
        MyBase.New(connection, "MRCashEntities")
        OnContextCreated()
    End Sub

    #End Region

    #Region "Partial Methods"

    Partial Private Sub OnContextCreated()
    End Sub

    #End Region

    #Region "ObjectSet Properties"

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    Public ReadOnly Property Acquisti() As ObjectSet(Of Acquisti)
        Get
            If (_Acquisti Is Nothing) Then
                _Acquisti = MyBase.CreateObjectSet(Of Acquisti)("Acquisti")
            End If
            Return _Acquisti
        End Get
    End Property

    Private _Acquisti As ObjectSet(Of Acquisti)

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    Public ReadOnly Property Fornitori() As ObjectSet(Of Fornitori)
        Get
            If (_Fornitori Is Nothing) Then
                _Fornitori = MyBase.CreateObjectSet(Of Fornitori)("Fornitori")
            End If
            Return _Fornitori
        End Get
    End Property

    Private _Fornitori As ObjectSet(Of Fornitori)

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    Public ReadOnly Property Oggetti() As ObjectSet(Of Oggetti)
        Get
            If (_Oggetti Is Nothing) Then
                _Oggetti = MyBase.CreateObjectSet(Of Oggetti)("Oggetti")
            End If
            Return _Oggetti
        End Get
    End Property

    Private _Oggetti As ObjectSet(Of Oggetti)

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    Public ReadOnly Property Vendite() As ObjectSet(Of Vendite)
        Get
            If (_Vendite Is Nothing) Then
                _Vendite = MyBase.CreateObjectSet(Of Vendite)("Vendite")
            End If
            Return _Vendite
        End Get
    End Property

    Private _Vendite As ObjectSet(Of Vendite)

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    Public ReadOnly Property V_AcquistiGiornalieri() As ObjectSet(Of V_AcquistiGiornalieri)
        Get
            If (_V_AcquistiGiornalieri Is Nothing) Then
                _V_AcquistiGiornalieri = MyBase.CreateObjectSet(Of V_AcquistiGiornalieri)("V_AcquistiGiornalieri")
            End If
            Return _V_AcquistiGiornalieri
        End Get
    End Property

    Private _V_AcquistiGiornalieri As ObjectSet(Of V_AcquistiGiornalieri)

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    Public ReadOnly Property V_Giornalieri() As ObjectSet(Of V_Giornalieri)
        Get
            If (_V_Giornalieri Is Nothing) Then
                _V_Giornalieri = MyBase.CreateObjectSet(Of V_Giornalieri)("V_Giornalieri")
            End If
            Return _V_Giornalieri
        End Get
    End Property

    Private _V_Giornalieri As ObjectSet(Of V_Giornalieri)

    #End Region

    #Region "AddTo Methods"

    ''' <summary>
    ''' Deprecated Method for adding a new object to the Acquisti EntitySet. Consider using the .Add method of the associated ObjectSet(Of T) property instead.
    ''' </summary>
    Public Sub AddToAcquisti(ByVal acquisti As Acquisti)
        MyBase.AddObject("Acquisti", acquisti)
    End Sub

    ''' <summary>
    ''' Deprecated Method for adding a new object to the Fornitori EntitySet. Consider using the .Add method of the associated ObjectSet(Of T) property instead.
    ''' </summary>
    Public Sub AddToFornitori(ByVal fornitori As Fornitori)
        MyBase.AddObject("Fornitori", fornitori)
    End Sub

    ''' <summary>
    ''' Deprecated Method for adding a new object to the Oggetti EntitySet. Consider using the .Add method of the associated ObjectSet(Of T) property instead.
    ''' </summary>
    Public Sub AddToOggetti(ByVal oggetti As Oggetti)
        MyBase.AddObject("Oggetti", oggetti)
    End Sub

    ''' <summary>
    ''' Deprecated Method for adding a new object to the Vendite EntitySet. Consider using the .Add method of the associated ObjectSet(Of T) property instead.
    ''' </summary>
    Public Sub AddToVendite(ByVal vendite As Vendite)
        MyBase.AddObject("Vendite", vendite)
    End Sub

    ''' <summary>
    ''' Deprecated Method for adding a new object to the V_AcquistiGiornalieri EntitySet. Consider using the .Add method of the associated ObjectSet(Of T) property instead.
    ''' </summary>
    Public Sub AddToV_AcquistiGiornalieri(ByVal v_AcquistiGiornalieri As V_AcquistiGiornalieri)
        MyBase.AddObject("V_AcquistiGiornalieri", v_AcquistiGiornalieri)
    End Sub

    ''' <summary>
    ''' Deprecated Method for adding a new object to the V_Giornalieri EntitySet. Consider using the .Add method of the associated ObjectSet(Of T) property instead.
    ''' </summary>
    Public Sub AddToV_Giornalieri(ByVal v_Giornalieri As V_Giornalieri)
        MyBase.AddObject("V_Giornalieri", v_Giornalieri)
    End Sub

    #End Region

    #Region "Function Imports"

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    Public Function Totali_Giornalieri() As ObjectResult(Of Oggetti)
        Return MyBase.ExecuteFunction(Of Oggetti)("Totali_Giornalieri")

    End Function
    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    ''' <param name="mergeOption"></param>
    Public Function Totali_Giornalieri(mergeOption As MergeOption) As ObjectResult(Of Oggetti)
        Return MyBase.ExecuteFunction(Of Oggetti)("Totali_Giornalieri", mergeOption)

    End Function

    #End Region

End Class

#End Region

#Region "Entities"

''' <summary>
''' No Metadata Documentation available.
''' </summary>
<EdmEntityTypeAttribute(NamespaceName:="MRCashModel", Name:="Acquisti")>
<Serializable()>
<DataContractAttribute(IsReference:=True)>
Public Partial Class Acquisti
    Inherits EntityObject
    #Region "Factory Method"

    ''' <summary>
    ''' Create a new Acquisti object.
    ''' </summary>
    ''' <param name="iDAcquisto">Initial value of the IDAcquisto property.</param>
    ''' <param name="data">Initial value of the Data property.</param>
    ''' <param name="transazione">Initial value of the Transazione property.</param>
    Public Shared Function CreateAcquisti(iDAcquisto As Global.System.Int32, data As Global.System.DateTime, transazione As Global.System.Int32) As Acquisti
        Dim acquisti as Acquisti = New Acquisti
        acquisti.IDAcquisto = iDAcquisto
        acquisti.Data = data
        acquisti.Transazione = transazione
        Return acquisti
    End Function

    #End Region

    #Region "Primitive Properties"

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property IDAcquisto() As Global.System.Int32
        Get
            Return _IDAcquisto
        End Get
        Set
            If (_IDAcquisto <> Value) Then
                OnIDAcquistoChanging(value)
                ReportPropertyChanging("IDAcquisto")
                _IDAcquisto = StructuralObject.SetValidValue(value)
                ReportPropertyChanged("IDAcquisto")
                OnIDAcquistoChanged()
            End If
        End Set
    End Property

    Private _IDAcquisto As Global.System.Int32
    Private Partial Sub OnIDAcquistoChanging(value As Global.System.Int32)
    End Sub

    Private Partial Sub OnIDAcquistoChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property Data() As Global.System.DateTime
        Get
            Return _Data
        End Get
        Set
            OnDataChanging(value)
            ReportPropertyChanging("Data")
            _Data = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("Data")
            OnDataChanged()
        End Set
    End Property

    Private _Data As Global.System.DateTime
    Private Partial Sub OnDataChanging(value As Global.System.DateTime)
    End Sub

    Private Partial Sub OnDataChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property Transazione() As Global.System.Int32
        Get
            Return _Transazione
        End Get
        Set
            OnTransazioneChanging(value)
            ReportPropertyChanging("Transazione")
            _Transazione = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("Transazione")
            OnTransazioneChanged()
        End Set
    End Property

    Private _Transazione As Global.System.Int32
    Private Partial Sub OnTransazioneChanging(value As Global.System.Int32)
    End Sub

    Private Partial Sub OnTransazioneChanged()
    End Sub

    #End Region

    #Region "Navigation Properties"

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <XmlIgnoreAttribute()>
    <SoapIgnoreAttribute()>
    <DataMemberAttribute()>
    <EdmRelationshipNavigationPropertyAttribute("MRCashModel", "FK_Acquisti_Fornitori", "Fornitori")>
    Public Property Fornitori() As Fornitori
        Get
            Return CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of Fornitori)("MRCashModel.FK_Acquisti_Fornitori", "Fornitori").Value
        End Get
        Set
            CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of Fornitori)("MRCashModel.FK_Acquisti_Fornitori", "Fornitori").Value = value
        End Set
    End Property
    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <BrowsableAttribute(False)>
    <DataMemberAttribute()>
    Public Property FornitoriReference() As EntityReference(Of Fornitori)
        Get
            Return CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of Fornitori)("MRCashModel.FK_Acquisti_Fornitori", "Fornitori")
        End Get
        Set
            If (Not value Is Nothing)
                CType(Me, IEntityWithRelationships).RelationshipManager.InitializeRelatedReference(Of Fornitori)("MRCashModel.FK_Acquisti_Fornitori", "Fornitori", value)
            End If
        End Set
    End Property

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <XmlIgnoreAttribute()>
    <SoapIgnoreAttribute()>
    <DataMemberAttribute()>
    <EdmRelationshipNavigationPropertyAttribute("MRCashModel", "FK_Oggetti_Acquisti", "Oggetti")>
     Public Property Oggetti() As EntityCollection(Of Oggetti)
        Get
            Return CType(Me,IEntityWithRelationships).RelationshipManager.GetRelatedCollection(Of Oggetti)("MRCashModel.FK_Oggetti_Acquisti", "Oggetti")
        End Get
        Set
            If (Not value Is Nothing)
                CType(Me, IEntityWithRelationships).RelationshipManager.InitializeRelatedCollection(Of Oggetti)("MRCashModel.FK_Oggetti_Acquisti", "Oggetti", value)
            End If
        End Set
    End Property

    #End Region

End Class

''' <summary>
''' No Metadata Documentation available.
''' </summary>
<EdmEntityTypeAttribute(NamespaceName:="MRCashModel", Name:="Fornitori")>
<Serializable()>
<DataContractAttribute(IsReference:=True)>
Public Partial Class Fornitori
    Inherits EntityObject
    #Region "Factory Method"

    ''' <summary>
    ''' Create a new Fornitori object.
    ''' </summary>
    ''' <param name="iDFornitore">Initial value of the IDFornitore property.</param>
    ''' <param name="dataRilascio">Initial value of the DataRilascio property.</param>
    ''' <param name="dataNascita">Initial value of the DataNascita property.</param>
    Public Shared Function CreateFornitori(iDFornitore As Global.System.Int32, dataRilascio As Global.System.DateTime, dataNascita As Global.System.DateTime) As Fornitori
        Dim fornitori as Fornitori = New Fornitori
        fornitori.IDFornitore = iDFornitore
        fornitori.DataRilascio = dataRilascio
        fornitori.DataNascita = dataNascita
        Return fornitori
    End Function

    #End Region

    #Region "Primitive Properties"

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property IDFornitore() As Global.System.Int32
        Get
            Return _IDFornitore
        End Get
        Set
            If (_IDFornitore <> Value) Then
                OnIDFornitoreChanging(value)
                ReportPropertyChanging("IDFornitore")
                _IDFornitore = StructuralObject.SetValidValue(value)
                ReportPropertyChanged("IDFornitore")
                OnIDFornitoreChanged()
            End If
        End Set
    End Property

    Private _IDFornitore As Global.System.Int32
    Private Partial Sub OnIDFornitoreChanging(value As Global.System.Int32)
    End Sub

    Private Partial Sub OnIDFornitoreChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property Cognome() As Global.System.String
        Get
            Return _Cognome
        End Get
        Set
            OnCognomeChanging(value)
            ReportPropertyChanging("Cognome")
            _Cognome = StructuralObject.SetValidValue(value, false)
            ReportPropertyChanged("Cognome")
            OnCognomeChanged()
        End Set
    End Property

    Private _Cognome As Global.System.String = " "
    Private Partial Sub OnCognomeChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnCognomeChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property Nome() As Global.System.String
        Get
            Return _Nome
        End Get
        Set
            OnNomeChanging(value)
            ReportPropertyChanging("Nome")
            _Nome = StructuralObject.SetValidValue(value, false)
            ReportPropertyChanged("Nome")
            OnNomeChanged()
        End Set
    End Property

    Private _Nome As Global.System.String = " "
    Private Partial Sub OnNomeChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnNomeChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property RifDoc() As Global.System.String
        Get
            Return _RifDoc
        End Get
        Set
            OnRifDocChanging(value)
            ReportPropertyChanging("RifDoc")
            _RifDoc = StructuralObject.SetValidValue(value, false)
            ReportPropertyChanged("RifDoc")
            OnRifDocChanged()
        End Set
    End Property

    Private _RifDoc As Global.System.String = " "
    Private Partial Sub OnRifDocChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnRifDocChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property Indirizzo() As Global.System.String
        Get
            Return _Indirizzo
        End Get
        Set
            OnIndirizzoChanging(value)
            ReportPropertyChanging("Indirizzo")
            _Indirizzo = StructuralObject.SetValidValue(value, false)
            ReportPropertyChanged("Indirizzo")
            OnIndirizzoChanged()
        End Set
    End Property

    Private _Indirizzo As Global.System.String = " "
    Private Partial Sub OnIndirizzoChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnIndirizzoChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property Citta() As Global.System.String
        Get
            Return _Citta
        End Get
        Set
            OnCittaChanging(value)
            ReportPropertyChanging("Citta")
            _Citta = StructuralObject.SetValidValue(value, false)
            ReportPropertyChanged("Citta")
            OnCittaChanged()
        End Set
    End Property

    Private _Citta As Global.System.String = " "
    Private Partial Sub OnCittaChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnCittaChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property Provincia() As Global.System.String
        Get
            Return _Provincia
        End Get
        Set
            OnProvinciaChanging(value)
            ReportPropertyChanging("Provincia")
            _Provincia = StructuralObject.SetValidValue(value, false)
            ReportPropertyChanged("Provincia")
            OnProvinciaChanged()
        End Set
    End Property

    Private _Provincia As Global.System.String = " "
    Private Partial Sub OnProvinciaChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnProvinciaChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property Telefono() As Global.System.String
        Get
            Return _Telefono
        End Get
        Set
            OnTelefonoChanging(value)
            ReportPropertyChanging("Telefono")
            _Telefono = StructuralObject.SetValidValue(value, false)
            ReportPropertyChanged("Telefono")
            OnTelefonoChanged()
        End Set
    End Property

    Private _Telefono As Global.System.String = " "
    Private Partial Sub OnTelefonoChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnTelefonoChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property Cap() As Global.System.String
        Get
            Return _Cap
        End Get
        Set
            OnCapChanging(value)
            ReportPropertyChanging("Cap")
            _Cap = StructuralObject.SetValidValue(value, false)
            ReportPropertyChanged("Cap")
            OnCapChanged()
        End Set
    End Property

    Private _Cap As Global.System.String = " "
    Private Partial Sub OnCapChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnCapChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property TipoDoc() As Global.System.String
        Get
            Return _TipoDoc
        End Get
        Set
            OnTipoDocChanging(value)
            ReportPropertyChanging("TipoDoc")
            _TipoDoc = StructuralObject.SetValidValue(value, false)
            ReportPropertyChanged("TipoDoc")
            OnTipoDocChanged()
        End Set
    End Property

    Private _TipoDoc As Global.System.String = " "
    Private Partial Sub OnTipoDocChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnTipoDocChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property DataRilascio() As Global.System.DateTime
        Get
            Return _DataRilascio
        End Get
        Set
            OnDataRilascioChanging(value)
            ReportPropertyChanging("DataRilascio")
            _DataRilascio = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("DataRilascio")
            OnDataRilascioChanged()
        End Set
    End Property

    Private _DataRilascio As Global.System.DateTime
    Private Partial Sub OnDataRilascioChanging(value As Global.System.DateTime)
    End Sub

    Private Partial Sub OnDataRilascioChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property DataNascita() As Global.System.DateTime
        Get
            Return _DataNascita
        End Get
        Set
            OnDataNascitaChanging(value)
            ReportPropertyChanging("DataNascita")
            _DataNascita = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("DataNascita")
            OnDataNascitaChanged()
        End Set
    End Property

    Private _DataNascita As Global.System.DateTime
    Private Partial Sub OnDataNascitaChanging(value As Global.System.DateTime)
    End Sub

    Private Partial Sub OnDataNascitaChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property Note() As Global.System.String
        Get
            Return _Note
        End Get
        Set
            OnNoteChanging(value)
            ReportPropertyChanging("Note")
            _Note = StructuralObject.SetValidValue(value, false)
            ReportPropertyChanged("Note")
            OnNoteChanged()
        End Set
    End Property

    Private _Note As Global.System.String = " "
    Private Partial Sub OnNoteChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnNoteChanged()
    End Sub

    #End Region

    #Region "Navigation Properties"

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <XmlIgnoreAttribute()>
    <SoapIgnoreAttribute()>
    <DataMemberAttribute()>
    <EdmRelationshipNavigationPropertyAttribute("MRCashModel", "FK_Acquisti_Fornitori", "Acquisti")>
     Public Property Acquisti() As EntityCollection(Of Acquisti)
        Get
            Return CType(Me,IEntityWithRelationships).RelationshipManager.GetRelatedCollection(Of Acquisti)("MRCashModel.FK_Acquisti_Fornitori", "Acquisti")
        End Get
        Set
            If (Not value Is Nothing)
                CType(Me, IEntityWithRelationships).RelationshipManager.InitializeRelatedCollection(Of Acquisti)("MRCashModel.FK_Acquisti_Fornitori", "Acquisti", value)
            End If
        End Set
    End Property

    #End Region

End Class

''' <summary>
''' No Metadata Documentation available.
''' </summary>
<EdmEntityTypeAttribute(NamespaceName:="MRCashModel", Name:="Oggetti")>
<Serializable()>
<DataContractAttribute(IsReference:=True)>
Public Partial Class Oggetti
    Inherits EntityObject
    #Region "Factory Method"

    ''' <summary>
    ''' Create a new Oggetti object.
    ''' </summary>
    ''' <param name="iDOggetto">Initial value of the IDOggetto property.</param>
    ''' <param name="prezzoAcquisto">Initial value of the PrezzoAcquisto property.</param>
    ''' <param name="prezzoStimato">Initial value of the PrezzoStimato property.</param>
    ''' <param name="prezzoVendita">Initial value of the PrezzoVendita property.</param>
    ''' <param name="rigaAcquisto">Initial value of the RigaAcquisto property.</param>
    ''' <param name="rigaVendita">Initial value of the RigaVendita property.</param>
    Public Shared Function CreateOggetti(iDOggetto As Global.System.Int32, prezzoAcquisto As Global.System.Decimal, prezzoStimato As Global.System.Decimal, prezzoVendita As Global.System.Decimal, rigaAcquisto As Global.System.Int32, rigaVendita As Global.System.Int32) As Oggetti
        Dim oggetti as Oggetti = New Oggetti
        oggetti.IDOggetto = iDOggetto
        oggetti.PrezzoAcquisto = prezzoAcquisto
        oggetti.PrezzoStimato = prezzoStimato
        oggetti.PrezzoVendita = prezzoVendita
        oggetti.RigaAcquisto = rigaAcquisto
        oggetti.RigaVendita = rigaVendita
        Return oggetti
    End Function

    #End Region

    #Region "Primitive Properties"

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property IDOggetto() As Global.System.Int32
        Get
            Return _IDOggetto
        End Get
        Set
            If (_IDOggetto <> Value) Then
                OnIDOggettoChanging(value)
                ReportPropertyChanging("IDOggetto")
                _IDOggetto = StructuralObject.SetValidValue(value)
                ReportPropertyChanged("IDOggetto")
                OnIDOggettoChanged()
            End If
        End Set
    End Property

    Private _IDOggetto As Global.System.Int32
    Private Partial Sub OnIDOggettoChanging(value As Global.System.Int32)
    End Sub

    Private Partial Sub OnIDOggettoChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property Codice() As Global.System.String
        Get
            Return _Codice
        End Get
        Set
            OnCodiceChanging(value)
            ReportPropertyChanging("Codice")
            _Codice = StructuralObject.SetValidValue(value, false)
            ReportPropertyChanged("Codice")
            OnCodiceChanged()
        End Set
    End Property

    Private _Codice As Global.System.String = " "
    Private Partial Sub OnCodiceChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnCodiceChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property Descrizione() As Global.System.String
        Get
            Return _Descrizione
        End Get
        Set
            OnDescrizioneChanging(value)
            ReportPropertyChanging("Descrizione")
            _Descrizione = StructuralObject.SetValidValue(value, false)
            ReportPropertyChanged("Descrizione")
            OnDescrizioneChanged()
        End Set
    End Property

    Private _Descrizione As Global.System.String = " "
    Private Partial Sub OnDescrizioneChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnDescrizioneChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property PrezzoAcquisto() As Global.System.Decimal
        Get
            Return _PrezzoAcquisto
        End Get
        Set
            OnPrezzoAcquistoChanging(value)
            ReportPropertyChanging("PrezzoAcquisto")
            _PrezzoAcquisto = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("PrezzoAcquisto")
            OnPrezzoAcquistoChanged()
        End Set
    End Property

    Private _PrezzoAcquisto As Global.System.Decimal
    Private Partial Sub OnPrezzoAcquistoChanging(value As Global.System.Decimal)
    End Sub

    Private Partial Sub OnPrezzoAcquistoChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property PrezzoStimato() As Global.System.Decimal
        Get
            Return _PrezzoStimato
        End Get
        Set
            OnPrezzoStimatoChanging(value)
            ReportPropertyChanging("PrezzoStimato")
            _PrezzoStimato = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("PrezzoStimato")
            OnPrezzoStimatoChanged()
        End Set
    End Property

    Private _PrezzoStimato As Global.System.Decimal
    Private Partial Sub OnPrezzoStimatoChanging(value As Global.System.Decimal)
    End Sub

    Private Partial Sub OnPrezzoStimatoChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property PrezzoVendita() As Global.System.Decimal
        Get
            Return _PrezzoVendita
        End Get
        Set
            OnPrezzoVenditaChanging(value)
            ReportPropertyChanging("PrezzoVendita")
            _PrezzoVendita = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("PrezzoVendita")
            OnPrezzoVenditaChanged()
        End Set
    End Property

    Private _PrezzoVendita As Global.System.Decimal
    Private Partial Sub OnPrezzoVenditaChanging(value As Global.System.Decimal)
    End Sub

    Private Partial Sub OnPrezzoVenditaChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property Modello() As Global.System.String
        Get
            Return _Modello
        End Get
        Set
            OnModelloChanging(value)
            ReportPropertyChanging("Modello")
            _Modello = StructuralObject.SetValidValue(value, true)
            ReportPropertyChanged("Modello")
            OnModelloChanged()
        End Set
    End Property

    Private _Modello As Global.System.String = " "
    Private Partial Sub OnModelloChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnModelloChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property Serie() As Global.System.String
        Get
            Return _Serie
        End Get
        Set
            OnSerieChanging(value)
            ReportPropertyChanging("Serie")
            _Serie = StructuralObject.SetValidValue(value, true)
            ReportPropertyChanged("Serie")
            OnSerieChanged()
        End Set
    End Property

    Private _Serie As Global.System.String = " "
    Private Partial Sub OnSerieChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnSerieChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property DataRientro() As Nullable(Of Global.System.DateTime)
        Get
            Return _DataRientro
        End Get
        Set
            OnDataRientroChanging(value)
            ReportPropertyChanging("DataRientro")
            _DataRientro = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("DataRientro")
            OnDataRientroChanged()
        End Set
    End Property

    Private _DataRientro As Nullable(Of Global.System.DateTime)
    Private Partial Sub OnDataRientroChanging(value As Nullable(Of Global.System.DateTime))
    End Sub

    Private Partial Sub OnDataRientroChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property DataRiconsegna() As Nullable(Of Global.System.DateTime)
        Get
            Return _DataRiconsegna
        End Get
        Set
            OnDataRiconsegnaChanging(value)
            ReportPropertyChanging("DataRiconsegna")
            _DataRiconsegna = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("DataRiconsegna")
            OnDataRiconsegnaChanged()
        End Set
    End Property

    Private _DataRiconsegna As Nullable(Of Global.System.DateTime)
    Private Partial Sub OnDataRiconsegnaChanging(value As Nullable(Of Global.System.DateTime))
    End Sub

    Private Partial Sub OnDataRiconsegnaChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property DataRottamazione() As Nullable(Of Global.System.DateTime)
        Get
            Return _DataRottamazione
        End Get
        Set
            OnDataRottamazioneChanging(value)
            ReportPropertyChanging("DataRottamazione")
            _DataRottamazione = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("DataRottamazione")
            OnDataRottamazioneChanged()
        End Set
    End Property

    Private _DataRottamazione As Nullable(Of Global.System.DateTime)
    Private Partial Sub OnDataRottamazioneChanging(value As Nullable(Of Global.System.DateTime))
    End Sub

    Private Partial Sub OnDataRottamazioneChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=true)>
    <DataMemberAttribute()>
    Public Property Note() As Global.System.String
        Get
            Return _Note
        End Get
        Set
            OnNoteChanging(value)
            ReportPropertyChanging("Note")
            _Note = StructuralObject.SetValidValue(value, true)
            ReportPropertyChanged("Note")
            OnNoteChanged()
        End Set
    End Property

    Private _Note As Global.System.String = " "
    Private Partial Sub OnNoteChanging(value As Global.System.String)
    End Sub

    Private Partial Sub OnNoteChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property RigaAcquisto() As Global.System.Int32
        Get
            Return _RigaAcquisto
        End Get
        Set
            OnRigaAcquistoChanging(value)
            ReportPropertyChanging("RigaAcquisto")
            _RigaAcquisto = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("RigaAcquisto")
            OnRigaAcquistoChanged()
        End Set
    End Property

    Private _RigaAcquisto As Global.System.Int32
    Private Partial Sub OnRigaAcquistoChanging(value As Global.System.Int32)
    End Sub

    Private Partial Sub OnRigaAcquistoChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property RigaVendita() As Global.System.Int32
        Get
            Return _RigaVendita
        End Get
        Set
            OnRigaVenditaChanging(value)
            ReportPropertyChanging("RigaVendita")
            _RigaVendita = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("RigaVendita")
            OnRigaVenditaChanged()
        End Set
    End Property

    Private _RigaVendita As Global.System.Int32
    Private Partial Sub OnRigaVenditaChanging(value As Global.System.Int32)
    End Sub

    Private Partial Sub OnRigaVenditaChanged()
    End Sub

    #End Region

    #Region "Navigation Properties"

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <XmlIgnoreAttribute()>
    <SoapIgnoreAttribute()>
    <DataMemberAttribute()>
    <EdmRelationshipNavigationPropertyAttribute("MRCashModel", "FK_Oggetti_Acquisti", "Acquisti")>
    Public Property Acquisti() As Acquisti
        Get
            Return CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of Acquisti)("MRCashModel.FK_Oggetti_Acquisti", "Acquisti").Value
        End Get
        Set
            CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of Acquisti)("MRCashModel.FK_Oggetti_Acquisti", "Acquisti").Value = value
        End Set
    End Property
    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <BrowsableAttribute(False)>
    <DataMemberAttribute()>
    Public Property AcquistiReference() As EntityReference(Of Acquisti)
        Get
            Return CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of Acquisti)("MRCashModel.FK_Oggetti_Acquisti", "Acquisti")
        End Get
        Set
            If (Not value Is Nothing)
                CType(Me, IEntityWithRelationships).RelationshipManager.InitializeRelatedReference(Of Acquisti)("MRCashModel.FK_Oggetti_Acquisti", "Acquisti", value)
            End If
        End Set
    End Property

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <XmlIgnoreAttribute()>
    <SoapIgnoreAttribute()>
    <DataMemberAttribute()>
    <EdmRelationshipNavigationPropertyAttribute("MRCashModel", "FK_Oggetti_Vendite", "Vendite")>
    Public Property Vendite() As Vendite
        Get
            Return CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of Vendite)("MRCashModel.FK_Oggetti_Vendite", "Vendite").Value
        End Get
        Set
            CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of Vendite)("MRCashModel.FK_Oggetti_Vendite", "Vendite").Value = value
        End Set
    End Property
    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <BrowsableAttribute(False)>
    <DataMemberAttribute()>
    Public Property VenditeReference() As EntityReference(Of Vendite)
        Get
            Return CType(Me, IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of Vendite)("MRCashModel.FK_Oggetti_Vendite", "Vendite")
        End Get
        Set
            If (Not value Is Nothing)
                CType(Me, IEntityWithRelationships).RelationshipManager.InitializeRelatedReference(Of Vendite)("MRCashModel.FK_Oggetti_Vendite", "Vendite", value)
            End If
        End Set
    End Property

    #End Region

End Class

''' <summary>
''' No Metadata Documentation available.
''' </summary>
<EdmEntityTypeAttribute(NamespaceName:="MRCashModel", Name:="V_AcquistiGiornalieri")>
<Serializable()>
<DataContractAttribute(IsReference:=True)>
Public Partial Class V_AcquistiGiornalieri
    Inherits EntityObject
    #Region "Factory Method"

    ''' <summary>
    ''' Create a new V_AcquistiGiornalieri object.
    ''' </summary>
    ''' <param name="data">Initial value of the Data property.</param>
    ''' <param name="totale">Initial value of the Totale property.</param>
    Public Shared Function CreateV_AcquistiGiornalieri(data As Global.System.DateTime, totale As Global.System.Decimal) As V_AcquistiGiornalieri
        Dim v_AcquistiGiornalieri as V_AcquistiGiornalieri = New V_AcquistiGiornalieri
        v_AcquistiGiornalieri.Data = data
        v_AcquistiGiornalieri.Totale = totale
        Return v_AcquistiGiornalieri
    End Function

    #End Region

    #Region "Primitive Properties"

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property Data() As Global.System.DateTime
        Get
            Return _Data
        End Get
        Set
            If (_Data <> Value) Then
                OnDataChanging(value)
                ReportPropertyChanging("Data")
                _Data = StructuralObject.SetValidValue(value)
                ReportPropertyChanged("Data")
                OnDataChanged()
            End If
        End Set
    End Property

    Private _Data As Global.System.DateTime
    Private Partial Sub OnDataChanging(value As Global.System.DateTime)
    End Sub

    Private Partial Sub OnDataChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property Totale() As Global.System.Decimal
        Get
            Return _Totale
        End Get
        Set
            If (_Totale <> Value) Then
                OnTotaleChanging(value)
                ReportPropertyChanging("Totale")
                _Totale = StructuralObject.SetValidValue(value)
                ReportPropertyChanged("Totale")
                OnTotaleChanged()
            End If
        End Set
    End Property

    Private _Totale As Global.System.Decimal
    Private Partial Sub OnTotaleChanging(value As Global.System.Decimal)
    End Sub

    Private Partial Sub OnTotaleChanged()
    End Sub

    #End Region

End Class

''' <summary>
''' No Metadata Documentation available.
''' </summary>
<EdmEntityTypeAttribute(NamespaceName:="MRCashModel", Name:="V_Giornalieri")>
<Serializable()>
<DataContractAttribute(IsReference:=True)>
Public Partial Class V_Giornalieri
    Inherits EntityObject
    #Region "Factory Method"

    ''' <summary>
    ''' Create a new V_Giornalieri object.
    ''' </summary>
    ''' <param name="iDVendita">Initial value of the IDVendita property.</param>
    ''' <param name="data">Initial value of the Data property.</param>
    ''' <param name="totale">Initial value of the Totale property.</param>
    Public Shared Function CreateV_Giornalieri(iDVendita As Global.System.Int32, data As Global.System.DateTime, totale As Global.System.Decimal) As V_Giornalieri
        Dim v_Giornalieri as V_Giornalieri = New V_Giornalieri
        v_Giornalieri.IDVendita = iDVendita
        v_Giornalieri.Data = data
        v_Giornalieri.Totale = totale
        Return v_Giornalieri
    End Function

    #End Region

    #Region "Primitive Properties"

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property IDVendita() As Global.System.Int32
        Get
            Return _IDVendita
        End Get
        Set
            If (_IDVendita <> Value) Then
                OnIDVenditaChanging(value)
                ReportPropertyChanging("IDVendita")
                _IDVendita = StructuralObject.SetValidValue(value)
                ReportPropertyChanged("IDVendita")
                OnIDVenditaChanged()
            End If
        End Set
    End Property

    Private _IDVendita As Global.System.Int32
    Private Partial Sub OnIDVenditaChanging(value As Global.System.Int32)
    End Sub

    Private Partial Sub OnIDVenditaChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property Data() As Global.System.DateTime
        Get
            Return _Data
        End Get
        Set
            OnDataChanging(value)
            ReportPropertyChanging("Data")
            _Data = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("Data")
            OnDataChanged()
        End Set
    End Property

    Private _Data As Global.System.DateTime
    Private Partial Sub OnDataChanging(value As Global.System.DateTime)
    End Sub

    Private Partial Sub OnDataChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property Totale() As Global.System.Decimal
        Get
            Return _Totale
        End Get
        Set
            OnTotaleChanging(value)
            ReportPropertyChanging("Totale")
            _Totale = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("Totale")
            OnTotaleChanged()
        End Set
    End Property

    Private _Totale As Global.System.Decimal
    Private Partial Sub OnTotaleChanging(value As Global.System.Decimal)
    End Sub

    Private Partial Sub OnTotaleChanged()
    End Sub

    #End Region

End Class

''' <summary>
''' No Metadata Documentation available.
''' </summary>
<EdmEntityTypeAttribute(NamespaceName:="MRCashModel", Name:="Vendite")>
<Serializable()>
<DataContractAttribute(IsReference:=True)>
Public Partial Class Vendite
    Inherits EntityObject
    #Region "Factory Method"

    ''' <summary>
    ''' Create a new Vendite object.
    ''' </summary>
    ''' <param name="iDVendita">Initial value of the IDVendita property.</param>
    ''' <param name="data">Initial value of the Data property.</param>
    Public Shared Function CreateVendite(iDVendita As Global.System.Int32, data As Global.System.DateTime) As Vendite
        Dim vendite as Vendite = New Vendite
        vendite.IDVendita = iDVendita
        vendite.Data = data
        Return vendite
    End Function

    #End Region

    #Region "Primitive Properties"

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property IDVendita() As Global.System.Int32
        Get
            Return _IDVendita
        End Get
        Set
            If (_IDVendita <> Value) Then
                OnIDVenditaChanging(value)
                ReportPropertyChanging("IDVendita")
                _IDVendita = StructuralObject.SetValidValue(value)
                ReportPropertyChanged("IDVendita")
                OnIDVenditaChanged()
            End If
        End Set
    End Property

    Private _IDVendita As Global.System.Int32
    Private Partial Sub OnIDVenditaChanging(value As Global.System.Int32)
    End Sub

    Private Partial Sub OnIDVenditaChanged()
    End Sub

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <EdmScalarPropertyAttribute(EntityKeyProperty:=false, IsNullable:=false)>
    <DataMemberAttribute()>
    Public Property Data() As Global.System.DateTime
        Get
            Return _Data
        End Get
        Set
            OnDataChanging(value)
            ReportPropertyChanging("Data")
            _Data = StructuralObject.SetValidValue(value)
            ReportPropertyChanged("Data")
            OnDataChanged()
        End Set
    End Property

    Private _Data As Global.System.DateTime
    Private Partial Sub OnDataChanging(value As Global.System.DateTime)
    End Sub

    Private Partial Sub OnDataChanged()
    End Sub

    #End Region

    #Region "Navigation Properties"

    ''' <summary>
    ''' No Metadata Documentation available.
    ''' </summary>
    <XmlIgnoreAttribute()>
    <SoapIgnoreAttribute()>
    <DataMemberAttribute()>
    <EdmRelationshipNavigationPropertyAttribute("MRCashModel", "FK_Oggetti_Vendite", "Oggetti")>
     Public Property Oggetti() As EntityCollection(Of Oggetti)
        Get
            Return CType(Me,IEntityWithRelationships).RelationshipManager.GetRelatedCollection(Of Oggetti)("MRCashModel.FK_Oggetti_Vendite", "Oggetti")
        End Get
        Set
            If (Not value Is Nothing)
                CType(Me, IEntityWithRelationships).RelationshipManager.InitializeRelatedCollection(Of Oggetti)("MRCashModel.FK_Oggetti_Vendite", "Oggetti", value)
            End If
        End Set
    End Property

    #End Region

End Class

#End Region


