'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Oggetti
    Public Property IDOggetto As Integer
    Public Property Codice As String = " "
    Public Property Descrizione As String = " "
    Public Property PrezzoAcquisto As Decimal
    Public Property PrezzoStimato As Decimal
    Public Property PrezzoVendita As Decimal
    Public Property Modello As String = " "
    Public Property Serie As String = " "
    Public Property DataRientro As Nullable(Of Date)
    Public Property DataRiconsegna As Nullable(Of Date)
    Public Property DataRottamazione As Nullable(Of Date)
    Public Property Note As String = " "
    Public Property RigaAcquisto As Integer
    Public Property RigaVendita As Integer

    Public Overridable Property Acquisti As Acquisti
    Public Overridable Property Vendite As Vendite

End Class
