'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.225
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

<Assembly: Global.System.Data.Objects.DataClasses.EdmSchemaAttribute("a9c74a8e-1034-47cb-8b65-8952975d5807"),  _
 Assembly: Global.System.Data.Objects.DataClasses.EdmRelationshipAttribute("MRCashModel", "FK_Acquisti_Fornitori", "Fornitori", Global.System.Data.Metadata.Edm.RelationshipMultiplicity.One, GetType(Fornitori), "Acquisti", Global.System.Data.Metadata.Edm.RelationshipMultiplicity.Many, GetType(Acquisti)),  _
 Assembly: Global.System.Data.Objects.DataClasses.EdmRelationshipAttribute("MRCashModel", "FK_Oggetti_Acquisti", "Acquisti", Global.System.Data.Metadata.Edm.RelationshipMultiplicity.One, GetType(Acquisti), "Oggetti", Global.System.Data.Metadata.Edm.RelationshipMultiplicity.Many, GetType(Oggetti)),  _
 Assembly: Global.System.Data.Objects.DataClasses.EdmRelationshipAttribute("MRCashModel", "FK_Oggetti_Vendite", "Vendite", Global.System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, GetType(Vendite), "Oggetti", Global.System.Data.Metadata.Edm.RelationshipMultiplicity.Many, GetType(Oggetti))> 

'Original file name:
'Generation date: 13/10/2012 14:53:00
'''<summary>
'''There are no comments for MRCashEntities in the schema.
'''</summary>
Partial Public Class MRCashEntities
    Inherits Global.System.Data.Objects.ObjectContext
    '''<summary>
    '''Initializes a new MRCashEntities object using the connection string found in the 'MRCashEntities' section of the application configuration file.
    '''</summary>
    Public Sub New()
        MyBase.New("name=MRCashEntities", "MRCashEntities")
        Me.OnContextCreated
    End Sub
    '''<summary>
    '''Initialize a new MRCashEntities object.
    '''</summary>
    Public Sub New(ByVal connectionString As String)
        MyBase.New(connectionString, "MRCashEntities")
        Me.OnContextCreated
    End Sub
    '''<summary>
    '''Initialize a new MRCashEntities object.
    '''</summary>
    Public Sub New(ByVal connection As Global.System.Data.EntityClient.EntityConnection)
        MyBase.New(connection, "MRCashEntities")
        Me.OnContextCreated
    End Sub
    Partial Private Sub OnContextCreated()
        End Sub
    '''<summary>
    '''There are no comments for Acquisti in the schema.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Public ReadOnly Property Acquisti() As Global.System.Data.Objects.ObjectQuery(Of Acquisti)
        Get
            If (Me._Acquisti Is Nothing) Then
                Me._Acquisti = MyBase.CreateQuery(Of Acquisti)("[Acquisti]")
            End If
            Return Me._Acquisti
        End Get
    End Property
    <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Private _Acquisti As Global.System.Data.Objects.ObjectQuery(Of Acquisti)
    '''<summary>
    '''There are no comments for Fornitori in the schema.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Public ReadOnly Property Fornitori() As Global.System.Data.Objects.ObjectQuery(Of Fornitori)
        Get
            If (Me._Fornitori Is Nothing) Then
                Me._Fornitori = MyBase.CreateQuery(Of Fornitori)("[Fornitori]")
            End If
            Return Me._Fornitori
        End Get
    End Property
    <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Private _Fornitori As Global.System.Data.Objects.ObjectQuery(Of Fornitori)
    '''<summary>
    '''There are no comments for Oggetti in the schema.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Public ReadOnly Property Oggetti() As Global.System.Data.Objects.ObjectQuery(Of Oggetti)
        Get
            If (Me._Oggetti Is Nothing) Then
                Me._Oggetti = MyBase.CreateQuery(Of Oggetti)("[Oggetti]")
            End If
            Return Me._Oggetti
        End Get
    End Property
    <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Private _Oggetti As Global.System.Data.Objects.ObjectQuery(Of Oggetti)
    '''<summary>
    '''There are no comments for Vendite in the schema.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Public ReadOnly Property Vendite() As Global.System.Data.Objects.ObjectQuery(Of Vendite)
        Get
            If (Me._Vendite Is Nothing) Then
                Me._Vendite = MyBase.CreateQuery(Of Vendite)("[Vendite]")
            End If
            Return Me._Vendite
        End Get
    End Property
    <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Private _Vendite As Global.System.Data.Objects.ObjectQuery(Of Vendite)
    '''<summary>
    '''There are no comments for V_Giornalieri in the schema.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Public ReadOnly Property V_Giornalieri() As Global.System.Data.Objects.ObjectQuery(Of V_Giornalieri)
        Get
            If (Me._V_Giornalieri Is Nothing) Then
                Me._V_Giornalieri = MyBase.CreateQuery(Of V_Giornalieri)("[V_Giornalieri]")
            End If
            Return Me._V_Giornalieri
        End Get
    End Property
    <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Private _V_Giornalieri As Global.System.Data.Objects.ObjectQuery(Of V_Giornalieri)
    '''<summary>
    '''There are no comments for V_AcquistiGiornalieri in the schema.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Public ReadOnly Property V_AcquistiGiornalieri() As Global.System.Data.Objects.ObjectQuery(Of V_AcquistiGiornalieri)
        Get
            If (Me._V_AcquistiGiornalieri Is Nothing) Then
                Me._V_AcquistiGiornalieri = MyBase.CreateQuery(Of V_AcquistiGiornalieri)("[V_AcquistiGiornalieri]")
            End If
            Return Me._V_AcquistiGiornalieri
        End Get
    End Property
    <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Private _V_AcquistiGiornalieri As Global.System.Data.Objects.ObjectQuery(Of V_AcquistiGiornalieri)
    '''<summary>
    '''There are no comments for Acquisti in the schema.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Public Sub AddToAcquisti(ByVal acquisti As Acquisti)
        MyBase.AddObject("Acquisti", acquisti)
    End Sub
    '''<summary>
    '''There are no comments for Fornitori in the schema.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Public Sub AddToFornitori(ByVal fornitori As Fornitori)
        MyBase.AddObject("Fornitori", fornitori)
    End Sub
    '''<summary>
    '''There are no comments for Oggetti in the schema.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Public Sub AddToOggetti(ByVal oggetti As Oggetti)
        MyBase.AddObject("Oggetti", oggetti)
    End Sub
    '''<summary>
    '''There are no comments for Vendite in the schema.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Public Sub AddToVendite(ByVal vendite As Vendite)
        MyBase.AddObject("Vendite", vendite)
    End Sub
    '''<summary>
    '''There are no comments for V_Giornalieri in the schema.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Public Sub AddToV_Giornalieri(ByVal v_Giornalieri As V_Giornalieri)
        MyBase.AddObject("V_Giornalieri", v_Giornalieri)
    End Sub
    '''<summary>
    '''There are no comments for V_AcquistiGiornalieri in the schema.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Public Sub AddToV_AcquistiGiornalieri(ByVal v_AcquistiGiornalieri As V_AcquistiGiornalieri)
        MyBase.AddObject("V_AcquistiGiornalieri", v_AcquistiGiornalieri)
    End Sub
    '''<summary>
    '''There are no comments for MRCashModel.Totali_Giornalieri in the schema.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Public Function Totali_Giornalieri() As Global.System.Data.Objects.ObjectResult(Of Oggetti)
        Return MyBase.ExecuteFunction(Of Oggetti)("Totali_Giornalieri")
    End Function
End Class
'''<summary>
'''There are no comments for MRCashModel.Acquisti in the schema.
'''</summary>
'''<KeyProperties>
'''IDAcquisto
'''</KeyProperties>
<Global.System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName:="MRCashModel", Name:="Acquisti"),  _
 Global.System.Runtime.Serialization.DataContractAttribute(IsReference:=true),  _
 Global.System.Serializable()>  _
Partial Public Class Acquisti
    Inherits Global.System.Data.Objects.DataClasses.EntityObject
    '''<summary>
    '''Create a new Acquisti object.
    '''</summary>
    '''<param name="iDAcquisto">Initial value of IDAcquisto.</param>
    '''<param name="data">Initial value of Data.</param>
    '''<param name="transazione">Initial value of Transazione.</param>
    <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Public Shared Function CreateAcquisti(ByVal iDAcquisto As Integer, ByVal data As Date, ByVal transazione As Integer) As Acquisti
        Dim acquisti As Acquisti = New Acquisti()
        acquisti.IDAcquisto = iDAcquisto
        acquisti.Data = data
        acquisti.Transazione = transazione
        Return acquisti
    End Function
    '''<summary>
    '''There are no comments for property IDAcquisto in the schema.
    '''</summary>
    <Global.System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false),  _
     Global.System.Runtime.Serialization.DataMemberAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Public Property IDAcquisto() As Integer
        Get
            Return Me._IDAcquisto
        End Get
        Set
            Me.OnIDAcquistoChanging(value)
            Me.ReportPropertyChanging("IDAcquisto")
            Me._IDAcquisto = Global.System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value)
            Me.ReportPropertyChanged("IDAcquisto")
            Me.OnIDAcquistoChanged
        End Set
    End Property
    <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Private _IDAcquisto As Integer
    <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Partial Private Sub OnIDAcquistoChanging(ByVal value As Integer)
        End Sub
    <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Partial Private Sub OnIDAcquistoChanged()
        End Sub
    '''<summary>
    '''There are no comments for property Data in the schema.
    '''</summary>
    <Global.System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable:=false),  _
     Global.System.Runtime.Serialization.DataMemberAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Public Property Data() As Date
        Get
            Return Me._Data
        End Get
        Set
            Me.OnDataChanging(value)
            Me.ReportPropertyChanging("Data")
            Me._Data = Global.System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value)
            Me.ReportPropertyChanged("Data")
            Me.OnDataChanged
        End Set
    End Property
    <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Private _Data As Date
    <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Partial Private Sub OnDataChanging(ByVal value As Date)
        End Sub
    <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Partial Private Sub OnDataChanged()
        End Sub
    '''<summary>
    '''There are no comments for property Transazione in the schema.
    '''</summary>
    <Global.System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable:=false),  _
     Global.System.Runtime.Serialization.DataMemberAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Public Property Transazione() As Integer
        Get
            Return Me._Transazione
        End Get
        Set
            Me.OnTransazioneChanging(value)
            Me.ReportPropertyChanging("Transazione")
            Me._Transazione = Global.System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value)
            Me.ReportPropertyChanged("Transazione")
            Me.OnTransazioneChanged
        End Set
    End Property
    <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Private _Transazione As Integer
    <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Partial Private Sub OnTransazioneChanging(ByVal value As Integer)
        End Sub
    <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Partial Private Sub OnTransazioneChanged()
        End Sub
    '''<summary>
    '''There are no comments for Fornitori in the schema.
    '''</summary>
    <Global.System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("MRCashModel", "FK_Acquisti_Fornitori", "Fornitori"),  _
     Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0"),  _
     Global.System.Xml.Serialization.XmlIgnoreAttribute(),  _
     Global.System.Xml.Serialization.SoapIgnoreAttribute(),  _
     Global.System.Runtime.Serialization.DataMemberAttribute()>  _
    Public Property Fornitori() As Fornitori
        Get
            Return CType(Me,Global.System.Data.Objects.DataClasses.IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of Fornitori)("MRCashModel.FK_Acquisti_Fornitori", "Fornitori").Value
        End Get
        Set
            CType(Me,Global.System.Data.Objects.DataClasses.IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of Fornitori)("MRCashModel.FK_Acquisti_Fornitori", "Fornitori").Value = value
        End Set
    End Property
    '''<summary>
    '''There are no comments for Fornitori in the schema.
    '''</summary>
    <Global.System.ComponentModel.BrowsableAttribute(false),  _
     Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0"),  _
     Global.System.Runtime.Serialization.DataMemberAttribute()>  _
    Public Property FornitoriReference() As Global.System.Data.Objects.DataClasses.EntityReference(Of Fornitori)
        Get
            Return CType(Me,Global.System.Data.Objects.DataClasses.IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of Fornitori)("MRCashModel.FK_Acquisti_Fornitori", "Fornitori")
        End Get
        Set
            If (Not (value) Is Nothing) Then
                CType(Me,Global.System.Data.Objects.DataClasses.IEntityWithRelationships).RelationshipManager.InitializeRelatedReference(Of Fornitori)("MRCashModel.FK_Acquisti_Fornitori", "Fornitori", value)
            End If
        End Set
    End Property
    '''<summary>
    '''There are no comments for Oggetti in the schema.
    '''</summary>
    <Global.System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("MRCashModel", "FK_Oggetti_Acquisti", "Oggetti"),  _
     Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0"),  _
     Global.System.Xml.Serialization.XmlIgnoreAttribute(),  _
     Global.System.Xml.Serialization.SoapIgnoreAttribute(),  _
     Global.System.Runtime.Serialization.DataMemberAttribute()>  _
    Public Property Oggetti() As Global.System.Data.Objects.DataClasses.EntityCollection(Of Oggetti)
        Get
            Return CType(Me,Global.System.Data.Objects.DataClasses.IEntityWithRelationships).RelationshipManager.GetRelatedCollection(Of Oggetti)("MRCashModel.FK_Oggetti_Acquisti", "Oggetti")
        End Get
        Set
            If (Not (value) Is Nothing) Then
                CType(Me,Global.System.Data.Objects.DataClasses.IEntityWithRelationships).RelationshipManager.InitializeRelatedCollection(Of Oggetti)("MRCashModel.FK_Oggetti_Acquisti", "Oggetti", value)
            End If
        End Set
    End Property
End Class
'''<summary>
'''There are no comments for MRCashModel.Fornitori in the schema.
'''</summary>
'''<KeyProperties>
'''IDFornitore
'''</KeyProperties>
<Global.System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName:="MRCashModel", Name:="Fornitori"),  _
 Global.System.Runtime.Serialization.DataContractAttribute(IsReference:=true),  _
 Global.System.Serializable()>  _
Partial Public Class Fornitori
    Inherits Global.System.Data.Objects.DataClasses.EntityObject
    '''<summary>
    '''Create a new Fornitori object.
    '''</summary>
    '''<param name="iDFornitore">Initial value of IDFornitore.</param>
    '''<param name="dataRilascio">Initial value of DataRilascio.</param>
    '''<param name="dataNascita">Initial value of DataNascita.</param>
    <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Public Shared Function CreateFornitori(ByVal iDFornitore As Integer, ByVal dataRilascio As Date, ByVal dataNascita As Date) As Fornitori
        Dim fornitori As Fornitori = New Fornitori()
        fornitori.IDFornitore = iDFornitore
        fornitori.DataRilascio = dataRilascio
        fornitori.DataNascita = dataNascita
        Return fornitori
    End Function
    '''<summary>
    '''There are no comments for property IDFornitore in the schema.
    '''</summary>
    <Global.System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false),  _
     Global.System.Runtime.Serialization.DataMemberAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Public Property IDFornitore() As Integer
        Get
            Return Me._IDFornitore
        End Get
        Set
            Me.OnIDFornitoreChanging(value)
            Me.ReportPropertyChanging("IDFornitore")
            Me._IDFornitore = Global.System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value)
            Me.ReportPropertyChanged("IDFornitore")
            Me.OnIDFornitoreChanged
        End Set
    End Property
    <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Private _IDFornitore As Integer
    <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Partial Private Sub OnIDFornitoreChanging(ByVal value As Integer)
        End Sub
    <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Partial Private Sub OnIDFornitoreChanged()
        End Sub
    '''<summary>
    '''There are no comments for property Cognome in the schema.
    '''</summary>
    <Global.System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable:=false),  _
     Global.System.Runtime.Serialization.DataMemberAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Public Property Cognome() As String
        Get
            Return Me._Cognome
        End Get
        Set
            Me.OnCognomeChanging(value)
            Me.ReportPropertyChanging("Cognome")
            Me._Cognome = Global.System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false)
            Me.ReportPropertyChanged("Cognome")
            Me.OnCognomeChanged
        End Set
    End Property
    <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Private _Cognome As String = " "
    <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Partial Private Sub OnCognomeChanging(ByVal value As String)
        End Sub
    <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Partial Private Sub OnCognomeChanged()
        End Sub
    '''<summary>
    '''There are no comments for property Nome in the schema.
    '''</summary>
    <Global.System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable:=false),  _
     Global.System.Runtime.Serialization.DataMemberAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Public Property Nome() As String
        Get
            Return Me._Nome
        End Get
        Set
            Me.OnNomeChanging(value)
            Me.ReportPropertyChanging("Nome")
            Me._Nome = Global.System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false)
            Me.ReportPropertyChanged("Nome")
            Me.OnNomeChanged
        End Set
    End Property
    <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Private _Nome As String = " "
    <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Partial Private Sub OnNomeChanging(ByVal value As String)
        End Sub
    <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Partial Private Sub OnNomeChanged()
        End Sub
    '''<summary>
    '''There are no comments for property RifDoc in the schema.
    '''</summary>
    <Global.System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable:=false),  _
     Global.System.Runtime.Serialization.DataMemberAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Public Property RifDoc() As String
        Get
            Return Me._RifDoc
        End Get
        Set
            Me.OnRifDocChanging(value)
            Me.ReportPropertyChanging("RifDoc")
            Me._RifDoc = Global.System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false)
            Me.ReportPropertyChanged("RifDoc")
            Me.OnRifDocChanged
        End Set
    End Property
    <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Private _RifDoc As String = " "
    <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Partial Private Sub OnRifDocChanging(ByVal value As String)
        End Sub
    <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Partial Private Sub OnRifDocChanged()
        End Sub
    '''<summary>
    '''There are no comments for property Indirizzo in the schema.
    '''</summary>
    <Global.System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable:=false),  _
     Global.System.Runtime.Serialization.DataMemberAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Public Property Indirizzo() As String
        Get
            Return Me._Indirizzo
        End Get
        Set
            Me.OnIndirizzoChanging(value)
            Me.ReportPropertyChanging("Indirizzo")
            Me._Indirizzo = Global.System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false)
            Me.ReportPropertyChanged("Indirizzo")
            Me.OnIndirizzoChanged
        End Set
    End Property
    <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Private _Indirizzo As String = " "
    <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Partial Private Sub OnIndirizzoChanging(ByVal value As String)
        End Sub
    <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Partial Private Sub OnIndirizzoChanged()
        End Sub
    '''<summary>
    '''There are no comments for property Citta in the schema.
    '''</summary>
    <Global.System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable:=false),  _
     Global.System.Runtime.Serialization.DataMemberAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Public Property Citta() As String
        Get
            Return Me._Citta
        End Get
        Set
            Me.OnCittaChanging(value)
            Me.ReportPropertyChanging("Citta")
            Me._Citta = Global.System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false)
            Me.ReportPropertyChanged("Citta")
            Me.OnCittaChanged
        End Set
    End Property
    <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Private _Citta As String = " "
    <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Partial Private Sub OnCittaChanging(ByVal value As String)
        End Sub
    <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Partial Private Sub OnCittaChanged()
        End Sub
    '''<summary>
    '''There are no comments for property Provincia in the schema.
    '''</summary>
    <Global.System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable:=false),  _
     Global.System.Runtime.Serialization.DataMemberAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Public Property Provincia() As String
        Get
            Return Me._Provincia
        End Get
        Set
            Me.OnProvinciaChanging(value)
            Me.ReportPropertyChanging("Provincia")
            Me._Provincia = Global.System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false)
            Me.ReportPropertyChanged("Provincia")
            Me.OnProvinciaChanged
        End Set
    End Property
    <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Private _Provincia As String = " "
    <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Partial Private Sub OnProvinciaChanging(ByVal value As String)
        End Sub
    <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Partial Private Sub OnProvinciaChanged()
        End Sub
    '''<summary>
    '''There are no comments for property Telefono in the schema.
    '''</summary>
    <Global.System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable:=false),  _
     Global.System.Runtime.Serialization.DataMemberAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Public Property Telefono() As String
        Get
            Return Me._Telefono
        End Get
        Set
            Me.OnTelefonoChanging(value)
            Me.ReportPropertyChanging("Telefono")
            Me._Telefono = Global.System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false)
            Me.ReportPropertyChanged("Telefono")
            Me.OnTelefonoChanged
        End Set
    End Property
    <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Private _Telefono As String = " "
    <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Partial Private Sub OnTelefonoChanging(ByVal value As String)
        End Sub
    <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Partial Private Sub OnTelefonoChanged()
        End Sub
    '''<summary>
    '''There are no comments for property Cap in the schema.
    '''</summary>
    <Global.System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable:=false),  _
     Global.System.Runtime.Serialization.DataMemberAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Public Property Cap() As String
        Get
            Return Me._Cap
        End Get
        Set
            Me.OnCapChanging(value)
            Me.ReportPropertyChanging("Cap")
            Me._Cap = Global.System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false)
            Me.ReportPropertyChanged("Cap")
            Me.OnCapChanged
        End Set
    End Property
    <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Private _Cap As String = " "
    <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Partial Private Sub OnCapChanging(ByVal value As String)
        End Sub
    <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Partial Private Sub OnCapChanged()
        End Sub
    '''<summary>
    '''There are no comments for property TipoDoc in the schema.
    '''</summary>
    <Global.System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable:=false),  _
     Global.System.Runtime.Serialization.DataMemberAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Public Property TipoDoc() As String
        Get
            Return Me._TipoDoc
        End Get
        Set
            Me.OnTipoDocChanging(value)
            Me.ReportPropertyChanging("TipoDoc")
            Me._TipoDoc = Global.System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false)
            Me.ReportPropertyChanged("TipoDoc")
            Me.OnTipoDocChanged
        End Set
    End Property
    <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Private _TipoDoc As String = " "
    <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Partial Private Sub OnTipoDocChanging(ByVal value As String)
        End Sub
    <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Partial Private Sub OnTipoDocChanged()
        End Sub
    '''<summary>
    '''There are no comments for property DataRilascio in the schema.
    '''</summary>
    <Global.System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable:=false),  _
     Global.System.Runtime.Serialization.DataMemberAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Public Property DataRilascio() As Date
        Get
            Return Me._DataRilascio
        End Get
        Set
            Me.OnDataRilascioChanging(value)
            Me.ReportPropertyChanging("DataRilascio")
            Me._DataRilascio = Global.System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value)
            Me.ReportPropertyChanged("DataRilascio")
            Me.OnDataRilascioChanged
        End Set
    End Property
    <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Private _DataRilascio As Date
    <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Partial Private Sub OnDataRilascioChanging(ByVal value As Date)
        End Sub
    <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Partial Private Sub OnDataRilascioChanged()
        End Sub
    '''<summary>
    '''There are no comments for property DataNascita in the schema.
    '''</summary>
    <Global.System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable:=false),  _
     Global.System.Runtime.Serialization.DataMemberAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Public Property DataNascita() As Date
        Get
            Return Me._DataNascita
        End Get
        Set
            Me.OnDataNascitaChanging(value)
            Me.ReportPropertyChanging("DataNascita")
            Me._DataNascita = Global.System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value)
            Me.ReportPropertyChanged("DataNascita")
            Me.OnDataNascitaChanged
        End Set
    End Property
    <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Private _DataNascita As Date
    <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Partial Private Sub OnDataNascitaChanging(ByVal value As Date)
        End Sub
    <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Partial Private Sub OnDataNascitaChanged()
        End Sub
    '''<summary>
    '''There are no comments for property Note in the schema.
    '''</summary>
    <Global.System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable:=false),  _
     Global.System.Runtime.Serialization.DataMemberAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Public Property Note() As String
        Get
            Return Me._Note
        End Get
        Set
            Me.OnNoteChanging(value)
            Me.ReportPropertyChanging("Note")
            Me._Note = Global.System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false)
            Me.ReportPropertyChanged("Note")
            Me.OnNoteChanged
        End Set
    End Property
    <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Private _Note As String = " "
    <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Partial Private Sub OnNoteChanging(ByVal value As String)
        End Sub
    <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Partial Private Sub OnNoteChanged()
        End Sub
    '''<summary>
    '''There are no comments for Acquisti in the schema.
    '''</summary>
    <Global.System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("MRCashModel", "FK_Acquisti_Fornitori", "Acquisti"),  _
     Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0"),  _
     Global.System.Xml.Serialization.XmlIgnoreAttribute(),  _
     Global.System.Xml.Serialization.SoapIgnoreAttribute(),  _
     Global.System.Runtime.Serialization.DataMemberAttribute()>  _
    Public Property Acquisti() As Global.System.Data.Objects.DataClasses.EntityCollection(Of Acquisti)
        Get
            Return CType(Me,Global.System.Data.Objects.DataClasses.IEntityWithRelationships).RelationshipManager.GetRelatedCollection(Of Acquisti)("MRCashModel.FK_Acquisti_Fornitori", "Acquisti")
        End Get
        Set
            If (Not (value) Is Nothing) Then
                CType(Me,Global.System.Data.Objects.DataClasses.IEntityWithRelationships).RelationshipManager.InitializeRelatedCollection(Of Acquisti)("MRCashModel.FK_Acquisti_Fornitori", "Acquisti", value)
            End If
        End Set
    End Property
End Class
'''<summary>
'''There are no comments for MRCashModel.Oggetti in the schema.
'''</summary>
'''<KeyProperties>
'''IDOggetto
'''</KeyProperties>
<Global.System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName:="MRCashModel", Name:="Oggetti"),  _
 Global.System.Runtime.Serialization.DataContractAttribute(IsReference:=true),  _
 Global.System.Serializable()>  _
Partial Public Class Oggetti
    Inherits Global.System.Data.Objects.DataClasses.EntityObject
    '''<summary>
    '''Create a new Oggetti object.
    '''</summary>
    '''<param name="iDOggetto">Initial value of IDOggetto.</param>
    '''<param name="prezzoAcquisto">Initial value of PrezzoAcquisto.</param>
    '''<param name="prezzoStimato">Initial value of PrezzoStimato.</param>
    '''<param name="prezzoVendita">Initial value of PrezzoVendita.</param>
    '''<param name="rigaAcquisto">Initial value of RigaAcquisto.</param>
    '''<param name="rigaVendita">Initial value of RigaVendita.</param>
    <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Public Shared Function CreateOggetti(ByVal iDOggetto As Integer, ByVal prezzoAcquisto As Decimal, ByVal prezzoStimato As Decimal, ByVal prezzoVendita As Decimal, ByVal rigaAcquisto As Integer, ByVal rigaVendita As Integer) As Oggetti
        Dim oggetti As Oggetti = New Oggetti()
        oggetti.IDOggetto = iDOggetto
        oggetti.PrezzoAcquisto = prezzoAcquisto
        oggetti.PrezzoStimato = prezzoStimato
        oggetti.PrezzoVendita = prezzoVendita
        oggetti.RigaAcquisto = rigaAcquisto
        oggetti.RigaVendita = rigaVendita
        Return oggetti
    End Function
    '''<summary>
    '''There are no comments for property IDOggetto in the schema.
    '''</summary>
    <Global.System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false),  _
     Global.System.Runtime.Serialization.DataMemberAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Public Property IDOggetto() As Integer
        Get
            Return Me._IDOggetto
        End Get
        Set
            Me.OnIDOggettoChanging(value)
            Me.ReportPropertyChanging("IDOggetto")
            Me._IDOggetto = Global.System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value)
            Me.ReportPropertyChanged("IDOggetto")
            Me.OnIDOggettoChanged
        End Set
    End Property
    <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Private _IDOggetto As Integer
    <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Partial Private Sub OnIDOggettoChanging(ByVal value As Integer)
        End Sub
    <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Partial Private Sub OnIDOggettoChanged()
        End Sub
    '''<summary>
    '''There are no comments for property Codice in the schema.
    '''</summary>
    <Global.System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable:=false),  _
     Global.System.Runtime.Serialization.DataMemberAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Public Property Codice() As String
        Get
            Return Me._Codice
        End Get
        Set
            Me.OnCodiceChanging(value)
            Me.ReportPropertyChanging("Codice")
            Me._Codice = Global.System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false)
            Me.ReportPropertyChanged("Codice")
            Me.OnCodiceChanged
        End Set
    End Property
    <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Private _Codice As String = " "
    <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Partial Private Sub OnCodiceChanging(ByVal value As String)
        End Sub
    <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Partial Private Sub OnCodiceChanged()
        End Sub
    '''<summary>
    '''There are no comments for property Descrizione in the schema.
    '''</summary>
    <Global.System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable:=false),  _
     Global.System.Runtime.Serialization.DataMemberAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Public Property Descrizione() As String
        Get
            Return Me._Descrizione
        End Get
        Set
            Me.OnDescrizioneChanging(value)
            Me.ReportPropertyChanging("Descrizione")
            Me._Descrizione = Global.System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false)
            Me.ReportPropertyChanged("Descrizione")
            Me.OnDescrizioneChanged
        End Set
    End Property
    <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Private _Descrizione As String = " "
    <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Partial Private Sub OnDescrizioneChanging(ByVal value As String)
        End Sub
    <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Partial Private Sub OnDescrizioneChanged()
        End Sub
    '''<summary>
    '''There are no comments for property PrezzoAcquisto in the schema.
    '''</summary>
    <Global.System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable:=false),  _
     Global.System.Runtime.Serialization.DataMemberAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Public Property PrezzoAcquisto() As Decimal
        Get
            Return Me._PrezzoAcquisto
        End Get
        Set
            Me.OnPrezzoAcquistoChanging(value)
            Me.ReportPropertyChanging("PrezzoAcquisto")
            Me._PrezzoAcquisto = Global.System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value)
            Me.ReportPropertyChanged("PrezzoAcquisto")
            Me.OnPrezzoAcquistoChanged
        End Set
    End Property
    <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Private _PrezzoAcquisto As Decimal
    <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Partial Private Sub OnPrezzoAcquistoChanging(ByVal value As Decimal)
        End Sub
    <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Partial Private Sub OnPrezzoAcquistoChanged()
        End Sub
    '''<summary>
    '''There are no comments for property PrezzoStimato in the schema.
    '''</summary>
    <Global.System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable:=false),  _
     Global.System.Runtime.Serialization.DataMemberAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Public Property PrezzoStimato() As Decimal
        Get
            Return Me._PrezzoStimato
        End Get
        Set
            Me.OnPrezzoStimatoChanging(value)
            Me.ReportPropertyChanging("PrezzoStimato")
            Me._PrezzoStimato = Global.System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value)
            Me.ReportPropertyChanged("PrezzoStimato")
            Me.OnPrezzoStimatoChanged
        End Set
    End Property
    <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Private _PrezzoStimato As Decimal
    <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Partial Private Sub OnPrezzoStimatoChanging(ByVal value As Decimal)
        End Sub
    <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Partial Private Sub OnPrezzoStimatoChanged()
        End Sub
    '''<summary>
    '''There are no comments for property PrezzoVendita in the schema.
    '''</summary>
    <Global.System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable:=false),  _
     Global.System.Runtime.Serialization.DataMemberAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Public Property PrezzoVendita() As Decimal
        Get
            Return Me._PrezzoVendita
        End Get
        Set
            Me.OnPrezzoVenditaChanging(value)
            Me.ReportPropertyChanging("PrezzoVendita")
            Me._PrezzoVendita = Global.System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value)
            Me.ReportPropertyChanged("PrezzoVendita")
            Me.OnPrezzoVenditaChanged
        End Set
    End Property
    <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Private _PrezzoVendita As Decimal
    <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Partial Private Sub OnPrezzoVenditaChanging(ByVal value As Decimal)
        End Sub
    <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Partial Private Sub OnPrezzoVenditaChanged()
        End Sub
    '''<summary>
    '''There are no comments for property Modello in the schema.
    '''</summary>
    <Global.System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable:=false),  _
     Global.System.Runtime.Serialization.DataMemberAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Public Property Modello() As String
        Get
            Return Me._Modello
        End Get
        Set
            Me.OnModelloChanging(value)
            Me.ReportPropertyChanging("Modello")
            Me._Modello = Global.System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false)
            Me.ReportPropertyChanged("Modello")
            Me.OnModelloChanged
        End Set
    End Property
    <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Private _Modello As String = " "
    <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Partial Private Sub OnModelloChanging(ByVal value As String)
        End Sub
    <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Partial Private Sub OnModelloChanged()
        End Sub
    '''<summary>
    '''There are no comments for property Serie in the schema.
    '''</summary>
    <Global.System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable:=false),  _
     Global.System.Runtime.Serialization.DataMemberAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Public Property Serie() As String
        Get
            Return Me._Serie
        End Get
        Set
            Me.OnSerieChanging(value)
            Me.ReportPropertyChanging("Serie")
            Me._Serie = Global.System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false)
            Me.ReportPropertyChanged("Serie")
            Me.OnSerieChanged
        End Set
    End Property
    <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Private _Serie As String = " "
    <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Partial Private Sub OnSerieChanging(ByVal value As String)
        End Sub
    <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Partial Private Sub OnSerieChanged()
        End Sub
    '''<summary>
    '''There are no comments for property DataRientro in the schema.
    '''</summary>
    <Global.System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(),  _
     Global.System.Runtime.Serialization.DataMemberAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Public Property DataRientro() As Global.System.Nullable(Of Date)
        Get
            Return Me._DataRientro
        End Get
        Set
            Me.OnDataRientroChanging(value)
            Me.ReportPropertyChanging("DataRientro")
            Me._DataRientro = Global.System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value)
            Me.ReportPropertyChanged("DataRientro")
            Me.OnDataRientroChanged
        End Set
    End Property
    <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Private _DataRientro As Global.System.Nullable(Of Date)
    <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Partial Private Sub OnDataRientroChanging(ByVal value As Global.System.Nullable(Of Date))
        End Sub
    <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Partial Private Sub OnDataRientroChanged()
        End Sub
    '''<summary>
    '''There are no comments for property DataRiconsegna in the schema.
    '''</summary>
    <Global.System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(),  _
     Global.System.Runtime.Serialization.DataMemberAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Public Property DataRiconsegna() As Global.System.Nullable(Of Date)
        Get
            Return Me._DataRiconsegna
        End Get
        Set
            Me.OnDataRiconsegnaChanging(value)
            Me.ReportPropertyChanging("DataRiconsegna")
            Me._DataRiconsegna = Global.System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value)
            Me.ReportPropertyChanged("DataRiconsegna")
            Me.OnDataRiconsegnaChanged
        End Set
    End Property
    <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Private _DataRiconsegna As Global.System.Nullable(Of Date)
    <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Partial Private Sub OnDataRiconsegnaChanging(ByVal value As Global.System.Nullable(Of Date))
        End Sub
    <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Partial Private Sub OnDataRiconsegnaChanged()
        End Sub
    '''<summary>
    '''There are no comments for property DataRottamazione in the schema.
    '''</summary>
    <Global.System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(),  _
     Global.System.Runtime.Serialization.DataMemberAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Public Property DataRottamazione() As Global.System.Nullable(Of Date)
        Get
            Return Me._DataRottamazione
        End Get
        Set
            Me.OnDataRottamazioneChanging(value)
            Me.ReportPropertyChanging("DataRottamazione")
            Me._DataRottamazione = Global.System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value)
            Me.ReportPropertyChanged("DataRottamazione")
            Me.OnDataRottamazioneChanged
        End Set
    End Property
    <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Private _DataRottamazione As Global.System.Nullable(Of Date)
    <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Partial Private Sub OnDataRottamazioneChanging(ByVal value As Global.System.Nullable(Of Date))
        End Sub
    <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Partial Private Sub OnDataRottamazioneChanged()
        End Sub
    '''<summary>
    '''There are no comments for property Note in the schema.
    '''</summary>
    <Global.System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable:=false),  _
     Global.System.Runtime.Serialization.DataMemberAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Public Property Note() As String
        Get
            Return Me._Note
        End Get
        Set
            Me.OnNoteChanging(value)
            Me.ReportPropertyChanging("Note")
            Me._Note = Global.System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value, false)
            Me.ReportPropertyChanged("Note")
            Me.OnNoteChanged
        End Set
    End Property
    <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Private _Note As String = " "
    <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Partial Private Sub OnNoteChanging(ByVal value As String)
        End Sub
    <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Partial Private Sub OnNoteChanged()
        End Sub
    '''<summary>
    '''There are no comments for property RigaAcquisto in the schema.
    '''</summary>
    <Global.System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable:=false),  _
     Global.System.Runtime.Serialization.DataMemberAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Public Property RigaAcquisto() As Integer
        Get
            Return Me._RigaAcquisto
        End Get
        Set
            Me.OnRigaAcquistoChanging(value)
            Me.ReportPropertyChanging("RigaAcquisto")
            Me._RigaAcquisto = Global.System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value)
            Me.ReportPropertyChanged("RigaAcquisto")
            Me.OnRigaAcquistoChanged
        End Set
    End Property
    <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Private _RigaAcquisto As Integer
    <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Partial Private Sub OnRigaAcquistoChanging(ByVal value As Integer)
        End Sub
    <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Partial Private Sub OnRigaAcquistoChanged()
        End Sub
    '''<summary>
    '''There are no comments for property RigaVendita in the schema.
    '''</summary>
    <Global.System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable:=false),  _
     Global.System.Runtime.Serialization.DataMemberAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Public Property RigaVendita() As Integer
        Get
            Return Me._RigaVendita
        End Get
        Set
            Me.OnRigaVenditaChanging(value)
            Me.ReportPropertyChanging("RigaVendita")
            Me._RigaVendita = Global.System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value)
            Me.ReportPropertyChanged("RigaVendita")
            Me.OnRigaVenditaChanged
        End Set
    End Property
    <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Private _RigaVendita As Integer
    <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Partial Private Sub OnRigaVenditaChanging(ByVal value As Integer)
        End Sub
    <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Partial Private Sub OnRigaVenditaChanged()
        End Sub
    '''<summary>
    '''There are no comments for Acquisti in the schema.
    '''</summary>
    <Global.System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("MRCashModel", "FK_Oggetti_Acquisti", "Acquisti"),  _
     Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0"),  _
     Global.System.Xml.Serialization.XmlIgnoreAttribute(),  _
     Global.System.Xml.Serialization.SoapIgnoreAttribute(),  _
     Global.System.Runtime.Serialization.DataMemberAttribute()>  _
    Public Property Acquisti() As Acquisti
        Get
            Return CType(Me,Global.System.Data.Objects.DataClasses.IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of Acquisti)("MRCashModel.FK_Oggetti_Acquisti", "Acquisti").Value
        End Get
        Set
            CType(Me,Global.System.Data.Objects.DataClasses.IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of Acquisti)("MRCashModel.FK_Oggetti_Acquisti", "Acquisti").Value = value
        End Set
    End Property
    '''<summary>
    '''There are no comments for Acquisti in the schema.
    '''</summary>
    <Global.System.ComponentModel.BrowsableAttribute(false),  _
     Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0"),  _
     Global.System.Runtime.Serialization.DataMemberAttribute()>  _
    Public Property AcquistiReference() As Global.System.Data.Objects.DataClasses.EntityReference(Of Acquisti)
        Get
            Return CType(Me,Global.System.Data.Objects.DataClasses.IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of Acquisti)("MRCashModel.FK_Oggetti_Acquisti", "Acquisti")
        End Get
        Set
            If (Not (value) Is Nothing) Then
                CType(Me,Global.System.Data.Objects.DataClasses.IEntityWithRelationships).RelationshipManager.InitializeRelatedReference(Of Acquisti)("MRCashModel.FK_Oggetti_Acquisti", "Acquisti", value)
            End If
        End Set
    End Property
    '''<summary>
    '''There are no comments for Vendite in the schema.
    '''</summary>
    <Global.System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("MRCashModel", "FK_Oggetti_Vendite", "Vendite"),  _
     Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0"),  _
     Global.System.Xml.Serialization.XmlIgnoreAttribute(),  _
     Global.System.Xml.Serialization.SoapIgnoreAttribute(),  _
     Global.System.Runtime.Serialization.DataMemberAttribute()>  _
    Public Property Vendite() As Vendite
        Get
            Return CType(Me,Global.System.Data.Objects.DataClasses.IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of Vendite)("MRCashModel.FK_Oggetti_Vendite", "Vendite").Value
        End Get
        Set
            CType(Me,Global.System.Data.Objects.DataClasses.IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of Vendite)("MRCashModel.FK_Oggetti_Vendite", "Vendite").Value = value
        End Set
    End Property
    '''<summary>
    '''There are no comments for Vendite in the schema.
    '''</summary>
    <Global.System.ComponentModel.BrowsableAttribute(false),  _
     Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0"),  _
     Global.System.Runtime.Serialization.DataMemberAttribute()>  _
    Public Property VenditeReference() As Global.System.Data.Objects.DataClasses.EntityReference(Of Vendite)
        Get
            Return CType(Me,Global.System.Data.Objects.DataClasses.IEntityWithRelationships).RelationshipManager.GetRelatedReference(Of Vendite)("MRCashModel.FK_Oggetti_Vendite", "Vendite")
        End Get
        Set
            If (Not (value) Is Nothing) Then
                CType(Me,Global.System.Data.Objects.DataClasses.IEntityWithRelationships).RelationshipManager.InitializeRelatedReference(Of Vendite)("MRCashModel.FK_Oggetti_Vendite", "Vendite", value)
            End If
        End Set
    End Property
End Class
'''<summary>
'''There are no comments for MRCashModel.Vendite in the schema.
'''</summary>
'''<KeyProperties>
'''IDVendita
'''</KeyProperties>
<Global.System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName:="MRCashModel", Name:="Vendite"),  _
 Global.System.Runtime.Serialization.DataContractAttribute(IsReference:=true),  _
 Global.System.Serializable()>  _
Partial Public Class Vendite
    Inherits Global.System.Data.Objects.DataClasses.EntityObject
    '''<summary>
    '''Create a new Vendite object.
    '''</summary>
    '''<param name="iDVendita">Initial value of IDVendita.</param>
    '''<param name="data">Initial value of Data.</param>
    <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Public Shared Function CreateVendite(ByVal iDVendita As Integer, ByVal data As Date) As Vendite
        Dim vendite As Vendite = New Vendite()
        vendite.IDVendita = iDVendita
        vendite.Data = data
        Return vendite
    End Function
    '''<summary>
    '''There are no comments for property IDVendita in the schema.
    '''</summary>
    <Global.System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false),  _
     Global.System.Runtime.Serialization.DataMemberAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Public Property IDVendita() As Integer
        Get
            Return Me._IDVendita
        End Get
        Set
            Me.OnIDVenditaChanging(value)
            Me.ReportPropertyChanging("IDVendita")
            Me._IDVendita = Global.System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value)
            Me.ReportPropertyChanged("IDVendita")
            Me.OnIDVenditaChanged
        End Set
    End Property
    <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Private _IDVendita As Integer
    <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Partial Private Sub OnIDVenditaChanging(ByVal value As Integer)
        End Sub
    <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Partial Private Sub OnIDVenditaChanged()
        End Sub
    '''<summary>
    '''There are no comments for property Data in the schema.
    '''</summary>
    <Global.System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(IsNullable:=false),  _
     Global.System.Runtime.Serialization.DataMemberAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Public Property Data() As Date
        Get
            Return Me._Data
        End Get
        Set
            Me.OnDataChanging(value)
            Me.ReportPropertyChanging("Data")
            Me._Data = Global.System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value)
            Me.ReportPropertyChanged("Data")
            Me.OnDataChanged
        End Set
    End Property
    <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Private _Data As Date
    <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Partial Private Sub OnDataChanging(ByVal value As Date)
        End Sub
    <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Partial Private Sub OnDataChanged()
        End Sub
    '''<summary>
    '''There are no comments for Oggetti in the schema.
    '''</summary>
    <Global.System.Data.Objects.DataClasses.EdmRelationshipNavigationPropertyAttribute("MRCashModel", "FK_Oggetti_Vendite", "Oggetti"),  _
     Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0"),  _
     Global.System.Xml.Serialization.XmlIgnoreAttribute(),  _
     Global.System.Xml.Serialization.SoapIgnoreAttribute(),  _
     Global.System.Runtime.Serialization.DataMemberAttribute()>  _
    Public Property Oggetti() As Global.System.Data.Objects.DataClasses.EntityCollection(Of Oggetti)
        Get
            Return CType(Me,Global.System.Data.Objects.DataClasses.IEntityWithRelationships).RelationshipManager.GetRelatedCollection(Of Oggetti)("MRCashModel.FK_Oggetti_Vendite", "Oggetti")
        End Get
        Set
            If (Not (value) Is Nothing) Then
                CType(Me,Global.System.Data.Objects.DataClasses.IEntityWithRelationships).RelationshipManager.InitializeRelatedCollection(Of Oggetti)("MRCashModel.FK_Oggetti_Vendite", "Oggetti", value)
            End If
        End Set
    End Property
End Class
'''<summary>
'''There are no comments for MRCashModel.V_Giornalieri in the schema.
'''</summary>
'''<KeyProperties>
'''IDVendita
'''</KeyProperties>
<Global.System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName:="MRCashModel", Name:="V_Giornalieri"),  _
 Global.System.Runtime.Serialization.DataContractAttribute(IsReference:=true),  _
 Global.System.Serializable()>  _
Partial Public Class V_Giornalieri
    Inherits Global.System.Data.Objects.DataClasses.EntityObject
    '''<summary>
    '''Create a new V_Giornalieri object.
    '''</summary>
    '''<param name="iDVendita">Initial value of IDVendita.</param>
    <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Public Shared Function CreateV_Giornalieri(ByVal iDVendita As Integer) As V_Giornalieri
        Dim v_Giornalieri As V_Giornalieri = New V_Giornalieri()
        v_Giornalieri.IDVendita = iDVendita
        Return v_Giornalieri
    End Function
    '''<summary>
    '''There are no comments for property IDVendita in the schema.
    '''</summary>
    <Global.System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false),  _
     Global.System.Runtime.Serialization.DataMemberAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Public Property IDVendita() As Integer
        Get
            Return Me._IDVendita
        End Get
        Set
            Me.OnIDVenditaChanging(value)
            Me.ReportPropertyChanging("IDVendita")
            Me._IDVendita = Global.System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value)
            Me.ReportPropertyChanged("IDVendita")
            Me.OnIDVenditaChanged
        End Set
    End Property
    <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Private _IDVendita As Integer
    <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Partial Private Sub OnIDVenditaChanging(ByVal value As Integer)
        End Sub
    <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Partial Private Sub OnIDVenditaChanged()
        End Sub
    '''<summary>
    '''There are no comments for property Totale in the schema.
    '''</summary>
    <Global.System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(),  _
     Global.System.Runtime.Serialization.DataMemberAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Public Property Totale() As Global.System.Nullable(Of Decimal)
        Get
            Return Me._Totale
        End Get
        Set
            Me.OnTotaleChanging(value)
            Me.ReportPropertyChanging("Totale")
            Me._Totale = Global.System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value)
            Me.ReportPropertyChanged("Totale")
            Me.OnTotaleChanged
        End Set
    End Property
    <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Private _Totale As Global.System.Nullable(Of Decimal)
    <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Partial Private Sub OnTotaleChanging(ByVal value As Global.System.Nullable(Of Decimal))
        End Sub
    <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Partial Private Sub OnTotaleChanged()
        End Sub
End Class
'''<summary>
'''There are no comments for MRCashModel.V_AcquistiGiornalieri in the schema.
'''</summary>
'''<KeyProperties>
'''Data
'''Totale
'''</KeyProperties>
<Global.System.Data.Objects.DataClasses.EdmEntityTypeAttribute(NamespaceName:="MRCashModel", Name:="V_AcquistiGiornalieri"),  _
 Global.System.Runtime.Serialization.DataContractAttribute(IsReference:=true),  _
 Global.System.Serializable()>  _
Partial Public Class V_AcquistiGiornalieri
    Inherits Global.System.Data.Objects.DataClasses.EntityObject
    '''<summary>
    '''Create a new V_AcquistiGiornalieri object.
    '''</summary>
    '''<param name="data">Initial value of Data.</param>
    '''<param name="totale">Initial value of Totale.</param>
    <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Public Shared Function CreateV_AcquistiGiornalieri(ByVal data As Date, ByVal totale As Decimal) As V_AcquistiGiornalieri
        Dim v_AcquistiGiornalieri As V_AcquistiGiornalieri = New V_AcquistiGiornalieri()
        v_AcquistiGiornalieri.Data = data
        v_AcquistiGiornalieri.Totale = totale
        Return v_AcquistiGiornalieri
    End Function
    '''<summary>
    '''There are no comments for property Data in the schema.
    '''</summary>
    <Global.System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false),  _
     Global.System.Runtime.Serialization.DataMemberAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Public Property Data() As Date
        Get
            Return Me._Data
        End Get
        Set
            Me.OnDataChanging(value)
            Me.ReportPropertyChanging("Data")
            Me._Data = Global.System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value)
            Me.ReportPropertyChanged("Data")
            Me.OnDataChanged
        End Set
    End Property
    <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Private _Data As Date
    <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Partial Private Sub OnDataChanging(ByVal value As Date)
        End Sub
    <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Partial Private Sub OnDataChanged()
        End Sub
    '''<summary>
    '''There are no comments for property Totale in the schema.
    '''</summary>
    <Global.System.Data.Objects.DataClasses.EdmScalarPropertyAttribute(EntityKeyProperty:=true, IsNullable:=false),  _
     Global.System.Runtime.Serialization.DataMemberAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Public Property Totale() As Decimal
        Get
            Return Me._Totale
        End Get
        Set
            Me.OnTotaleChanging(value)
            Me.ReportPropertyChanging("Totale")
            Me._Totale = Global.System.Data.Objects.DataClasses.StructuralObject.SetValidValue(value)
            Me.ReportPropertyChanged("Totale")
            Me.OnTotaleChanged
        End Set
    End Property
    <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Private _Totale As Decimal
    <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Partial Private Sub OnTotaleChanging(ByVal value As Decimal)
        End Sub
    <Global.System.CodeDom.Compiler.GeneratedCode("System.Data.Entity.Design.EntityClassGenerator", "4.0.0.0")>  _
    Partial Private Sub OnTotaleChanged()
        End Sub
End Class
